version: '3.8'

services:
  api:
    build: .
    container_name: legal-analyzer-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    entrypoint: >
      bash -c "
        ollama serve &
        sleep 3 &&
        ollama pull llama3 &&
        tail -f /dev/null
      "

volumes:
  chroma_data:
  ollama_data: